-- CREATE DATABASE MYDB;

-- Creat table
CREATE TABLE 연습(
	이메일 VARCHAR(20),
	비밀번호 VARCHAR(20),
	나이 INT
);

CREATE TABLE 연습1(
	이메일 VARCHAR(20),
	비밀번호 VARCHAR(20),
	나이 INT,
	PRIMARY KEY (이메일)
);

CREATE TABLE MEMBER(
	NUM INT,
	NAME VARCHAR(20),
	AGE INT,
	EMAIL VARCHAR(20),
	PHONE VARCHAR(20),
	PRIMARY KEY (NUM)
);

--Alter table

ALTER TABLE 연습
	ADD PRIMARY KEY (이메일);

ALTER TABLE 연습
	ADD 대상 VARCHAR(20);
	
ALTER TABLE 연습
	ADD FOREIGN KEY (대상)
	REFERENCES 연습1 (이메일);

-- Foreign key

CREATE TABLE 부서 (
 부서번호 INT,
 부서이름 VARCHAR(10),
 PRIMARY KEY(부서번호)
);

CREATE TABLE 사원 (
 사원번호 INT,
 사원이름 VARCHAR(10),
 소속부서 INT,
 PRIMARY KEY(사원번호),
 FOREIGN KEY(소속부서) REFERENCES 부서(부서번호)
);

-- 전체 응용 문제 풀이
CREATE TABLE DEPT(
	DEPTO TINYINT,
	DNAME VARCHAR(14),
	LOC VARCHAR(13)
);

ALTER TABLE DEPT
	ADD PRIMARY KEY (DEPTO);



CREATE TABLE EMP(
	EMPNO INT,
	ENAME VARCHAR(10),
	JOB VARCHAR(9),
	MGR INT,
	HIREDATE DATETIME,
	SAL INT,
	COMM INT,
	DEPTO TINYINT,
	PRIMARY KEY (EMPNO),
	FOREIGN KEY (DEPTO) REFERENCES DEPT (DEPTO)
);

DESC MEMBER;  #TABLE의 현 상태 확인

ALTER TABLE MEMBER
	DROP AGE;
	
ALTER TABLE MEMBER
	MODIFY EMAIL VARCHAR(100);

-- FOREIGN KET의 제약조건을 바꾸려면 기존의 것을 지우고 새로 만들어야 함
-- 1) Foreign key의 제약조건 검색
SELECT * FROM TABLE_CONSTRAINTS #information_schema에 있는 TABLE
SELECT * FROM information_schema.TABLE_CONSTRAINTS

-- 2) 기존 제약조건 삭제
ALTER TABLE EMP DROP FOREIGN KEY EMP_IBFK_1;
 
 -- 3) 새로운 제약조건 만들기
 ALTER TABLE EMP ADD
  CONSTRAINT FK_EMP_DEPT
  FOREIGN KEY (DEPTO) REFERENCES DEPT(DEPTO)
  ON DELETE CASCADE; #연결된 PRIMARY KEY가 삭제되면 자동 값 제거(CASCADE)

DESC EMP;