-- ROUND(DATA, 반올림자리)
SELECT ROUNG(123.321, 1);
SELECT SAL * 0.5, ROUND(SAL * 0.5, 0) FROM EMP;

-- SUBSTR(DATA, 시작위치(1 부터), 개수)
SELECT SUBSTR(HIREDATE, 1, 10) FROM EMP;

-- CONCAT
SELECT * FROM EMP
 WHERE ENAME LIKE '%A%'; #파이썬 등 다른 언어와 같이 쓰면 작동안함
SELECT * FROM EMP
 WHERE ENAME LIKE CONCAT('%', 'A', '%');
 
-- NOW(), DATE_FORMAT()
SELECT NOW();
SELECT DATE_FORMAT(NOW(), '%Y / %M / %D');