CREATE TABLE NOODLE (
 NUM INT
 , NAME VARCHAR(50)
 , COMPANY VARCHAR(10)
 , KIND VARCHAR(1)
 , PRICE INT
 , E_DATE DATETIME
);


INSERT INTO NOODLE VALUES (
 1, '안성탕면', '농심', 'M', 700, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (noodle
 1, '김치라면', '삼양', 'M', 700, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
 1, '진라면', '오뚜기', 'C', 800, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
 1, '꼬꼬면', '팔도', 'C', 1000, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
 2, '신라면', '농심', 'C', 1100, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
 2, '삼양라면', '삼양', 'M', 700, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
 3, '너구리', '농심', 'M', 850, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
 3, '나가사키짬뽕', '삼양', 'C', 1300, NOW() + INTERVAL 3 MONTH);
INSERT INTO NOODLE VALUES (
 4, '짜파게티', '농심', 'C', 1200, NOW() + INTERVAL 3 MONTH);

-- 문제 시작
-- 1번
SELECT COMPANY, CONCAT(COUNT(1), 'c')
FROM NOODLE
GROUP BY COMPANY;

-- 2번
SELECT COMPANY, CONCAT(COUNT(1), 'c')
FROM NOODLE
GROUP BY COMPANY
ORDER BY COUNT(1) ASC;

-- 3번
SELECT COMPANY, CONCAT(COUNT(1), 'c')
FROM NOODLE
GROUP BY COMPANY
HAVING COUNT(1) >= 3;

-- 4번
SELECT NAME, COMPANY, DATE_FORMAT(E_DATE, '%YY %mM %dD')
FROM NOODLE
WHERE KIND = 'M' AND PRICE >= 800;

-- 5번
SELECT CONCAT(MAX(PRICE), 'WON')
FROM NOODLE
WHERE KIND = 'C';

-- 6번
SELECT COMPANY, MIN(PRICE)
FROM NOODLE
GROUP BY COMPANY;

-- 7번
SELECT COMPANY, SUM(PRICE)
FROM NOODLE
GROUP BY COMPANY
ORDER BY SUM(PRICE);

-- 8번
SELECT COMPANY, ROUND(AVG(PRICE), 1)
FROM NOODLE
GROUP BY COMPANY;