-- 1번
SELECT COUNT(*) AS 전체방문자수
FROM VISITOR_TB;

-- 2번
SELECT IP_ADDRESS, COUNT(*)
FROM VISITOR_TB
GROUP BY IP_ADDRESS
HAVING COUNT(*) > 2;

-- 3번
SELECT DATE_FORMAT(VST_TIME,'%Y'), COUNT(*)
FROM VISITOR_TB
GROUP BY DATE_FORMAT(VST_TIME,'%Y');

-- 4번
SELECT DATE_FORMAT(VST_TIME,'%m'), COUNT(*)
FROM VISITOR_TB
GROUP BY DATE_FORMAT(VST_TIME,'%m');

-- 5번
SELECT DATE_FORMAT(VST_TIME,'%Y-%m'), VST_PATH, COUNT(*)
FROM VISITOR_TB
GROUP BY DATE_FORMAT(VST_TIME,'%Y %m'), VST_PATH;