CREATE TABLE IT_MEMBER (
 NUM INT
 , NAME VARCHAR(10)
 , COURSE_NO INT
);
INSERT INTO IT_MEMBER VALUES (1, 'AA', 1);
INSERT INTO IT_MEMBER VALUES (2, 'BB', 1);
INSERT INTO IT_MEMBER VALUES (3, 'CC', 2);
INSERT INTO IT_MEMBER VALUES (4, 'DD', 2);
INSERT INTO IT_MEMBER VALUES (5, 'EE', 4);
INSERT INTO IT_MEMBER VALUES (6, 'FF', NULL);

CREATE TABLE COURSE02 (
 COURSE_NO INT
 , COURSE_NAME VARCHAR(20)
);
INSERT INTO COURSE02 VALUES (1, 'DIGITAL');
INSERT INTO COURSE02 VALUES (2, 'BIG DATA');
INSERT INTO COURSE02 VALUES (3, 'CLOUD');
INSERT INTO COURSE02 VALUES (4, 'NFC');


-- 문제 시작
SELECT * FROM IT_MEMBER;
SELECT * FROM COURSE02;

-- 1번
SELECT *
FROM IT_MEMBER I
JOIN COURSE02 C
ON I.COURSE_NO = C.COURSE_NO;

SELECT * FROM IT_MEMBER;
SELECT * FROM COURSE02;
-- 2번
SELECT *
FROM IT_MEMBER I
LEFT JOIN COURSE02 C
ON I.COURSE_NO = C.COURSE_NO;

-- 3번
SELECT NUM, NAME, C.COURSE_NO, COURSE_NAME
FROM COURSE02 C
RIGHT JOIN IT_MEMBER I
ON I.COURSE_NO = C.COURSE_NO;